# Generated by Django 5.0.6 on 2024-07-02 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('main_cate_name', models.CharField(max_length=20)),
                ('cate_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(default='F', max_length=1, null=True)),
                ('birthday', models.DateField(null=True)),
                ('address', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_company', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('item_create_date', models.DateTimeField(auto_now_add=True)),
                ('item_soldout', models.CharField(default='N', max_length=1)),
                ('item_is_display', models.CharField(max_length=1)),
                ('cate_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.category')),
                ('item_company', models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='items/')),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opt_color', models.CharField(max_length=10)),
                ('opt_size', models.CharField(default='FREE', max_length=5)),
                ('opt_item_soldout', models.CharField(default='N', max_length=1)),
                ('opt_stock', models.IntegerField(default=0)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_order_amount', models.IntegerField()),
                ('cart_create_date', models.DateTimeField(auto_now_add=True)),
                ('cust_no', models.ForeignKey(limit_choices_to={'is_company': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('opt_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.itemoption')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_no', models.ForeignKey(limit_choices_to={'is_company': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_create_date', models.DateTimeField(auto_now_add=True)),
                ('order_payment_status', models.CharField(default='결제완료', max_length=15, null=True)),
                ('order_payment_method', models.CharField(default='신용/체크', max_length=15)),
                ('order_total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cust_address', models.CharField(max_length=256)),
                ('cust_no', models.ForeignKey(limit_choices_to={'is_company': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_amount', models.IntegerField()),
                ('review_enabled', models.CharField(default='N', max_length=255, null=True)),
                ('order_product_status', models.CharField(default='주문완료', max_length=15)),
                ('opt_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.itemoption')),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shopapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_star', models.DecimalField(decimal_places=0, max_digits=1)),
                ('review_contents', models.CharField(max_length=150)),
                ('review_create_date', models.DateTimeField(auto_now_add=True)),
                ('review_image', models.CharField(default='0', max_length=300, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shopapp.item')),
                ('orderproduct_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.orderproduct')),
            ],
        ),
    ]
