# Generated by Django 5.0.6 on 2024-06-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_manageraccount_last_login_manageraccount_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageraccount',
            name='manager_pwd',
        ),
    ]
