# Generated by Django 5.0.6 on 2024-07-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_user_address_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_status',
            field=models.CharField(choices=[('준비중', '준비중'), ('배송시작', '배송시작'), ('배송완료', '배송완료')], default='준비중', max_length=10),
        ),
    ]
