# Generated by Django 5.0.6 on 2024-07-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_item_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
