# Generated by Django 5.0.6 on 2024-07-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_item_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoption',
            name='opt_size',
            field=models.CharField(default='FREE', max_length=10),
        ),
    ]
