# Generated by Django 5.0.6 on 2024-08-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_itemoption_opt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shopapp.order'),
        ),
    ]
