# Generated by Django 5.0.6 on 2024-08-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_alter_orderproduct_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='orderproduct_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.orderproduct'),
        ),
    ]
